#
# This file contains configuration flags to customize your site
#

name: Matias Volgyi
description: I salut you
longdescription: presenting myself. 

# for contact page
email: matias.volgyi@gmail.com

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/772100

resume:
  name: Matias Volgyi
  tagline: Software Developer
  summary: 'I am a system administrator with 7+ years of experience. Now working on my new challenge, become a full-time software developer.'
  email: matias.volgyi@gmail.com
  phone: 
  website: #blog.webjeda.com #do not add http://
  linkedin: mvolgyi
  github: mvolgyi
  twitter: '@mvolgyi'


# Includes an icon in the footer for each username you enter
footer-links:
  email: matias.volgyi@gmail.com
  github: mvolgyi
  rss: .

baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Include these folders.
include: ["_pages"]

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
